CREATE TABLE "FIREEMBLEM"."HERO" (
"ID" NUMBER(11) NOT NULL ENABLE, --PRIMARYKEY
"MASTER_ID" NUMBER(11) NOT NULL ENABLE, --关联主表主键
"TITLE_NAME" VARCHAR2(40) NOT NULL ENABLE, --称号
"NAME" VARCHAR2(40) NOT NULL ENABLE, --角色名
"NICK_NAME" VARCHAR2(40) DEFAULT NULL, --昵称
"IMG_NAME" VARCHAR2(50) DEFAULT NULL, --/resource/img/img_#{replace}#
"ORIGIN" VARCHAR2(40) DEFAULT NULL, --作品
"HP" NUMBER(3) DEFAULT NULL, --生命值
"ATTACT" NUMBER(3) DEFAULT NULL, --攻击
"SPEED" NUMBER(3) DEFAULT NULL, --速度
"DEF" NUMBER(3) DEFAULT NULL, --防御
"MDF" NUMBER(3) DEFAULT NULL, --魔防
"WEAPON" VARCHAR2(40) DEFAULT NULL, --50
"SKILL_A" VARCHAR2(40) DEFAULT NULL, --40
"SKILL_B" VARCHAR2(40) DEFAULT NULL, --25
"SKILL_C" VARCHAR2(40) DEFAULT NULL, --19
"SKILL_D" VARCHAR2(40) DEFAULT NULL, --21
"SKILL_S" VARCHAR2(40) DEFAULT NULL, --40
"SKILL_E" VARCHAR2(40) DEFAULT NULL, --30
"LIMIT_PLUS" NUMBER(2) DEFAULT NULL, --10
"DRAGON_FLOWER" NUMBER(2) DEFAULT NULL, --5
"SUPPORT_MATE" NUMBER(11) DEFAULT NULL, --154
"BLESSING" VARCHAR2(3) DEFAULT NULL, --000
"MOVE_TYPE" VARCHAR2(2) DEFAULT NULL, --00
"WEAPON_TYPE" VARCHAR2(3) DEFAULT NULL, --000
"COLOR" VARCHAR2(3) DEFAULT NULL, --000
"RACE" VARCHAR2(3) DEFAULT NULL, --000
"HERO_TYPE" VARCHAR2(3) DEFAULT NULL, --000
"TEAM" NUMBER(2) DEFAULT NULL, --00
"SKILL_POINT" NUMBER(5) DEFAULT NULL, --0000
"HERO_POINT" NUMBER(5) DEFAULT NULL, --0000
"SPEC_TAG" VARCHAR2(30) DEFAULT NULL, --特效标签
"POOL" VARCHAR2(30) DEFAULT NULL, --卡池
"FAVORITE" VARCHAR2(2) DEFAULT NULL, --00
"RANK" VARCHAR2(1) DEFAULT NULL, --S
"CREATE_DATETIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP, --登录日期
"UPDATE_DATETIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP, --更新日期
PRIMARY KEY ("ID"));